FROM ubuntu:20.04

# Arguments passed in at build time
ARG default_realm

RUN apt-get update

# Unattended krb5-user install
RUN DEBIAN_FRONTEND=noninteractive apt-get -yq install krb5-user

# Backup krb5.conf
RUN mv /etc/krb5.conf /etc/krb5.conf.example

# Pass in realm information for ktutil into krb5.conf
RUN echo -e "[libdefaults]\ndefault_realm = $default_realm\ndns_lookup_realm = true\ndns_lookup_kdc = true" > /etc/krb5.conf 

# Working directory
RUN mkdir azure-arc
WORKDIR "/azure-arc"

# Download script from microsoft/azure_arc
RUN apt-get -yq install wget
RUN wget https://raw.githubusercontent.com/microsoft/azure_arc/main/arc_data_services/deploy/scripts/create-sql-keytab.sh
RUN chmod u+x create-sql-keytab.sh

# Change to bash
SHELL ["/bin/bash", "-c"]